// created by liuhan on 2023/12/8
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
/*
 * ██   ██ ███████ ██      ██  ██████  ███████
 * ██   ██ ██      ██      ██ ██    ██ ██
 * ███████ █████   ██      ██ ██    ██ ███████
 * ██   ██ ██      ██      ██ ██    ██      ██
 * ██   ██ ███████ ███████ ██  ██████  ███████
 */
#pragma once

#include "rclcpp/rclcpp.hpp"
#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "realtime_tools/realtime_box.h"
#include "realtime_tools/realtime_publisher.h"
#include "rclcpp_lifecycle/state.hpp"
#include "lifecycle_msgs/msg/state.hpp"
#include "angles/angles.h"

#include "helios_control_interfaces/msg/motor_state.hpp"
#include "helios_control_interfaces/msg/motor_states.hpp"
#include "helios_control_interfaces/msg/gimbal_cmd.hpp"
#include "sensor_interfaces/msg/imu_euler.hpp"
#include "geometry_msgs/msg/twist_stamped.hpp"
#include "geometry_msgs/msg/transform_stamped.hpp"
#include "std_msgs/msg/float64.hpp"


#include "visibility_control.h"
#include "chassis/OmnidirectionalSolver.hpp"

#include <map>
#include <memory>
#include <vector>
#include <queue>
#include <string>
#include <chrono>

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "chassis_controller_parameters.hpp"

namespace helios_control {

constexpr auto DEFAULT_COMMAND_TOPIC = "/chassis_cmd_vel";
constexpr auto DEFAULT_COMMAND_OUT_TOPIC = "/chassis_cmd_vel_out";

using Params = chassis_controller::Params;
using ParamsListener = chassis_controller::ParamListener;

class ChassisController : public controller_interface::ControllerInterface {
public: 
    CHASSIS_CONTROLLER_PUBLIC
    ChassisController() = default;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_init() override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::InterfaceConfiguration command_interface_configuration() const override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::InterfaceConfiguration state_interface_configuration() const override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State &previous_state) override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_cleanup(const rclcpp_lifecycle::State& previous_state) override;

    CHASSIS_CONTROLLER_PUBLIC
    controller_interface::return_type update(const rclcpp::Time &time, const rclcpp::Duration &period) override;
protected:
    // Controller state
    int motor_number_;
    int state_interface_number_;
    int command_interface_number_;
    std::vector<std::string> motor_names_;

    // Chassis Solvers
    std::shared_ptr<BaseChassisSolver> chassis_solver_;

    // Publishers and subscribers
    std::shared_ptr<realtime_tools::RealtimePublisher<helios_control_interfaces::msg::MotorStates>> realtime_gimbal_state_pub_;
    rclcpp::Publisher<helios_control_interfaces::msg::MotorStates>::SharedPtr state_pub_;
    
    realtime_tools::RealtimeBox<std::shared_ptr<geometry_msgs::msg::TwistStamped>> received_gimbal_cmd_ptr_;
    realtime_tools::RealtimeBox<std::shared_ptr<std_msgs::msg::Float64>> received_yaw_diff_ptr_;

    rclcpp::Subscription<geometry_msgs::msg::TwistStamped>::SharedPtr cmd_sub_;
    rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr yaw_position_sub_;

    // Parameters from ROS for OmnidirectionalController
    std::shared_ptr<ParamsListener> param_listener_;
    Params params_;

    // publish rate limiter
    double publish_rate_ = 1000.0;
    rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
    rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};
    // Timeout to consider cmd commands old
    std::chrono::milliseconds cmd_timeout_{50};
    bool should_publish_ = false;

    std::map<std::string, double> wheel_res_;
    std::map<std::string, math_utilities::MotorPacket> cmd_map_;

    /**
     * @brief Convert the current state of the chassis from state_interfaces to a ROS message
     * @param state_msg The message to be filled
     */
    bool export_state_interfaces(helios_control_interfaces::msg::MotorStates& state_msg);

    bool is_halted_ = false;
    bool subscriber_is_active_ = false;
    bool reset();
    void halt();
    rclcpp::Logger logger_ = rclcpp::get_logger("CHASSIS_CONTROLLER");

};

} // namespace helios_control
