// created by liuhan on 2023/9/22
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
#pragma once

#include "rclcpp/rclcpp.hpp"
#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "realtime_tools/realtime_box.h"
#include "realtime_tools/realtime_publisher.h"
#include "rclcpp_lifecycle/state.hpp"
#include "lifecycle_msgs/msg/state.hpp"

#include "geometry_msgs/msg/twist_stamped.hpp"
#include "helios_rs_interfaces/msg/motor_state.hpp"
#include "helios_rs_interfaces/msg/motor_states.hpp"

#include "visibility_control.h"

#include <vector>
#include <queue>
#include <string>
#include <map>

#include "math_utilities/PID.hpp"
// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "shooter_controller_parameters.hpp"


namespace helios_control {

constexpr auto DEFAULT_COMMAND_TOPIC = "/shooter/cmd_vel";
constexpr auto DEFAULT_COMMAND_OUT_TOPIC = "/shooter/cmd_vel_out";

using Params = shooter_controller::Params;
using ParamsListener = shooter_controller::ParamListener;

typedef struct MotorCmd {
    int can_id;
    int motor_type;
    int motor_id;
    int value;
}MotorCmd;


class ShooterController : public controller_interface::ControllerInterface {
public:
    SHOOTER_CONTROLLER_PUBLIC
    ShooterController() = default;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_init() override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::InterfaceConfiguration command_interface_configuration() const override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::InterfaceConfiguration state_interface_configuration() const override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_configure(const rclcpp_lifecycle::State &previous_state) override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_activate(const rclcpp_lifecycle::State & previous_state) override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_deactivate(const rclcpp_lifecycle::State & previous_state) override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::CallbackReturn on_cleanup(const rclcpp_lifecycle::State& previous_state) override;

    SHOOTER_CONTROLLER_PUBLIC
    controller_interface::return_type update(const rclcpp::Time &time, const rclcpp::Duration &period) override;
protected:
    std::shared_ptr<realtime_tools::RealtimePublisher<helios_rs_interfaces::msg::MotorStates>> realtime_gimbal_state_pub_;
    rclcpp::Publisher<helios_rs_interfaces::msg::MotorStates>::SharedPtr state_pub_;
    
    realtime_tools::RealtimeBox<std::shared_ptr<geometry_msgs::msg::TwistStamped>> received_gimbal_cmd_ptr_;

    rclcpp::Subscription<geometry_msgs::msg::TwistStamped>::SharedPtr cmd_sub_;
    // Parameters from ROS for OmnidirectionalController
    std::shared_ptr<ParamsListener> param_listener_;
    Params params_;

    // publish rate limiter
    double publish_rate_ = 1000.0;
    rclcpp::Duration publish_period_ = rclcpp::Duration::from_nanoseconds(0);
    rclcpp::Time previous_publish_timestamp_{0, 0, RCL_CLOCK_UNINITIALIZED};
    // Timeout to consider cmd commands old
    std::chrono::milliseconds cmd_timeout_{50};

    // // previous 2 commands
    std::queue<geometry_msgs::msg::TwistStamped> previous_commands_;

    bool should_publish_ = false;
    // PID class
    std::map<std::string, math_utilities::PID> position_pids_;
    std::map<std::string, math_utilities::PID> velocity_pids_;
    int pid_cnt_ = 0;
    std::map<std::string, double> wheel_res_;
    std::map<std::string, MotorCmd> cmd_map_;
    /**
     * @brief Convert the current state of the chassis from state_interfaces to a ROS message
     * @param state_msg The message to be filled
     */
    bool export_state_interfaces(helios_rs_interfaces::msg::MotorStates& state_msg);

    bool is_halted_ = false;
    bool subscriber_is_active_ = false;
    bool reset();
    void halt();

    rclcpp::Logger logger_ = rclcpp::get_logger("Shooter_Controller");
};



} // namespace helios_control