// created by liuhan on 2023/12/8
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
/*
 * ██   ██ ███████ ██      ██  ██████  ███████
 * ██   ██ ██      ██      ██ ██    ██ ██
 * ███████ █████   ██      ██ ██    ██ ███████
 * ██   ██ ██      ██      ██ ██    ██      ██
 * ██   ██ ███████ ███████ ██  ██████  ███████
 */
#pragma once

#include <rclcpp/rclcpp.hpp>

#include <angles/angles.h>

#include "helios_control_interfaces/msg/gimbal_cmd.hpp"
#include "sensor_interfaces/msg/imu_euler.hpp"

#include "hardware_interface/loaned_state_interface.hpp"

#include "math_utilities/MotorPacket.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "gimbal_controller_parameters.hpp"


namespace helios_control {

typedef enum {
    AUTOAIM = 1,
    CRUISE = 2,
    DEBUG = 0,
    UNDEFINED = 3,
} GimbalState;

typedef enum {
    DEBUG_POSITION = 0,
    DEBUG_VELOCITY = 1,
} DebugMode;

class Gimbal {
public: 
    Gimbal(const gimbal_controller::Params& params);

    ~Gimbal();

    void set_gimbal_cmd(const helios_control_interfaces::msg::GimbalCmd& gimbal_cmd,
                        const sensor_interfaces::msg::ImuEuler& imu_euler,
                        double chassis_rotation_vel);

    void update_moto(std::map<std::string, math_utilities::MotorPacket>& cmd_map, 
                        const std::vector<hardware_interface::LoanedStateInterface>& state_interfaces);

    void update_params(const gimbal_controller::Params& params);

    double caculate_diff_angle_from_imu_to_chassis();

    math_utilities::MotorPacket* yaw_moto_ptr_;
    math_utilities::MotorPacket* pitch_moto_ptr_;
private:
    void do_debug(const helios_control_interfaces::msg::GimbalCmd& gimbal_cmd, double chassis_rotation_vel);

    void do_cruise(double yaw_vel, double pitch_vel, double chassis_rotation_vel);

    void do_autoaim(double yaw_angle, double pitch_angle);

    void do_undefined(const helios_control_interfaces::msg::GimbalCmd& gimbal_cmd, double chassis_rotation_vel);

    GimbalState last_state_;
    int pitch_vel_flag_ = 1;
    int accel_cnt_ = 0;
    int last_pitch_angle_ = 0;

    double last_autoaim_msg_time_;

    gimbal_controller::Params params_;
    
    int imu_round_cnt_;
    double imu_total_yaw_;
    double last_imu_yaw_;
    double imu_pitch_;

    rclcpp::Logger logger_ = rclcpp::get_logger("Gimbal");
};

} // namespace helios_control