// created by liuhan on 2023/12/8
// Submodule of HeliosRobotSystem
// for more see document: https://swjtuhelios.feishu.cn/docx/MfCsdfRxkoYk3oxWaazcfUpTnih?from=from_copylink
/*
 * ██   ██ ███████ ██      ██  ██████  ███████
 * ██   ██ ██      ██      ██ ██    ██ ██
 * ███████ █████   ██      ██ ██    ██ ███████
 * ██   ██ ██      ██      ██ ██    ██      ██
 * ██   ██ ███████ ███████ ██  ██████  ███████
 */
#pragma once

#include <rclcpp/rclcpp.hpp>

#include <angles/angles.h>

#include "helios_control_interfaces/msg/gimbal_cmd.hpp"
#include "hardware_interface/loaned_state_interface.hpp"

#include "math_utilities/MotorPacket.hpp"

// auto generated by ros2 generate_parameter_library
// https://github.com/PickNikRobotics/generate_parameter_library
#include "gimbal_controller_parameters.hpp"


namespace helios_control {

typedef enum {
    AUTOAIM,
    CRUISE,
    DEBUG,
    UNDEFINED,
} GimbalState;

typedef enum {
    DEBUG_POSITION,
    DEBUG_VELOCITY,
} DebugMode;

class Gimbal {
public: 
    Gimbal(const gimbal_controller::Params& params);

    ~Gimbal();

    void set_gimbal_cmd(const helios_control_interfaces::msg::GimbalCmd& gimbal_cmd);

    void update_moto(std::map<std::string, math_utilities::MotorPacket>& cmd_map, 
                        const std::vector<hardware_interface::LoanedStateInterface>& state_interfaces);

    void update_params(const gimbal_controller::Params& params);

private:
    void do_debug(const helios_control_interfaces::msg::GimbalCmd& gimbal_cmd);

    void do_cruise(double yaw_vel, double pitch_vel);

    void do_autoaim(double yaw_angle, double pitch_angle);

    void do_undefined(const helios_control_interfaces::msg::GimbalCmd& gimbal_cmd);

    GimbalState last_state_;

    double last_autoaim_msg_time_;

    gimbal_controller::Params params_;

    math_utilities::MotorPacket* yaw_moto_ptr_;
    math_utilities::MotorPacket* pitch_moto_ptr_;

    rclcpp::Logger logger_ = rclcpp::get_logger("Gimbal");
};

} // namespace helios_control